[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]] # toml syntax
repo = 'cespare/vim-toml'

[[plugins]] # nerdtree
repo = 'scrooloose/nerdtree'

[[plugins]] # unite
repo = 'Shougo/unite.vim'

[[plugins]] # commentout
repo = 'scrooloose/nerdcommenter'


