

filetype on
set autoindent
set autoread
set cindent
set clipboard=unnamed
set cursorcolumn
set cursorline
set expandtab
set fenc=utf-8
set hidden
set history=1000
set incsearch
set laststatus=2
set nobackup
set nocompatible
set noswapfile
set shiftwidth=2
set shiftwidth=2
set showcmd
set showmatch
set smartindent
set softtabstop=0
set tabstop=2
set virtualedit=onemore
set visualbell
set wildmenu
set wildmode=list:longest
syntax on
