set number
set ruler
set clipboard=unnamed
set fenc=utf-8
set nobackup
set noswapfile
set autoread
set hidden
set showcmd
set cursorline
set cursorcolumn
set virtualedit=onemore
set autoindent
set visualbell
set showmatch
set laststatus=2
set wildmode=list:longest
set list listchars=tab:\▸\-
set expandtab
set tabstop=2
set shiftwidth=2
set incsearch
set hlsearch
set softtabstop=0
set cindent
set nobackup
set nocompatible

syntax enable
