[[plugins]]
repo = 'Shougo/dein.vim'


[[plugins]] # nerdtree
repo = 'scrooloose/nerdtree'

[[plugins]] # unite
repo = 'Shougo/unite.vim'

[[plugins]] # commentout
repo = 'scrooloose/nerdcommenter'


